package org.emmef.cheapsets;

import java.util.Set;

import com.google.common.collect.testing.TestSetGenerator;
import com.google.common.collect.testing.features.Feature;

public interface TestFeatures {
	/**
	 * Returns the set of features that need to be tested for the {@link Set}s generated by this {@link TestSetGenerator}. 
	 * @return a non-{@code null} set of features. 
	 */
	public Iterable<Feature<?>> features();
	
	/**
	 * Return the name of the type of set being tested.
	 * @return a non-{@code null} name.
	 */
	public String getName(); 
}
